# 실행할 컨테이너 서비스들을 정의합니다.
services:
  # 'web'이라는 이름의 서비스를 선언합니다.
  web:
    # 현재 디렉토리 기준 ./web 폴더에 있는 Dockerfile을 사용하여 이미지를 빌드합니다.
    build: ./web
    # 호스트(로컬)의 8000번 포트와 컨테이너 내부의 8000번 포트를 연결(포트 포워딩)합니다.
    ports:
      - "8000:8000"
    # 컨테이너 내부에 주입할 환경 변수들을 설정합니다.
    environment:
      PORT: 8000
      APP_MODE: development